apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: copy-config
        image: busybox:latest
        command: ["/bin/sh", "-c", "cp /config/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf"]
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials  # Reference the secret name
              key: POSTGRES_PASSWORD  # Reference the key in the secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: config-volume
        configMap:
          name: mypostgres-conf
